name: Update CIDRs

on:
  workflow_dispatch:
  schedule:
  - cron: "20 3 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: 'xc2/10775fab2ad1edad0ad31e0b80774180'
        ref: 'main'
        path: 'cidr-gist'
        token: ${{ secrets.GIST_TOKEN }}
        github-server-url: 'https://gist.github.com'
    - run: |
        pushd cidr-gist
        git config user.name github-actions
        git config user.email github-actions@github.com
        popd

    - run: sudo apt update -y && sudo apt install -y aggregate whois jq
    
    - name: Update CIDRs
      run: make -C cidrs GEOIP_LICENSE=${{ secrets.GEOIP_LICENSE }}

    - name: Push to gist
      run: |
        cp -f cidrs/netflix-aws.txt cidr-gist/netflix-aws.txt
        cp -f cidrs/netflix-aws-us-west-2.txt cidr-gist/netflix-aws-us-west-2.txt
        cp -f cidrs/non-china-list.txt cidr-gist/non-china.txt
        cp -f cidrs/china-list.txt cidr-gist/china.txt
        cd cidr-gist
        git add .
        git commit -m 'Update CIDRs' || true
        echo "# Useful CIDRs
        
        | File | CIDRs | Last Updated |
        | - | - | - |" > README.md
        git ls-files -- '*.txt' | while read line; do
          count=$(cat "$line" | grep -v "^$" | grep -v '^#' | wc -l | awk '{printf "%'"'"'d", $1}')
          updated=$(git log -1 --pretty="format:%ci" -- "$line")
          echo "| [$line](https://gist.githubusercontent.com/xc2/10775fab2ad1edad0ad31e0b80774180/raw/${line}) | $count | $updated |" >> README.md
        done
        git add README.md
        git commit -m 'Update metadata' || true
        git push origin HEAD || true

    # - uses: exuanbo/actions-deploy-gist@v1
    #   with:
    #     token: ${{ secrets.GIST_TOKEN }}
    #     gist_id: 10775fab2ad1edad0ad31e0b80774180
    #     gist_file_name: netflix-aws.txt
    #     file_path: cidrs/netflix-aws.txt
    #     file_type: binary
    # - uses: exuanbo/actions-deploy-gist@v1
    #   with:
    #     token: ${{ secrets.GIST_TOKEN }}
    #     gist_id: 10775fab2ad1edad0ad31e0b80774180
    #     gist_file_name: netflix-aws-us-west-2.txt
    #     file_path: cidrs/netflix-aws-us-west-2.txt
    #     file_type: binary
    # - uses: exuanbo/actions-deploy-gist@v1
    #   with:
    #     token: ${{ secrets.GIST_TOKEN }}
    #     gist_id: 10775fab2ad1edad0ad31e0b80774180
    #     gist_file_name: non-china.txt
    #     file_path: cidrs/non-china-list.txt
    #     file_type: binary
    # - uses: exuanbo/actions-deploy-gist@v1
    #   with:
    #     token: ${{ secrets.GIST_TOKEN }}
    #     gist_id: 10775fab2ad1edad0ad31e0b80774180
    #     gist_file_name: china.txt
    #     file_path: cidrs/china-list.txt
    #     file_type: binary
