name: Update CIDRs

on:
  workflow_dispatch:
  schedule:
  - cron: "20 3 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: sudo apt update -y && sudo apt install -y aggregate whois jq
    - uses: actions/checkout@v3
    - name: Update CIDRs
      run: make -C cidrs GEOIP_LICENSE=${{ secrets.GEOIP_LICENSE }}

    - uses: actions/checkout@v3
      with:
        repository: 'xc2/10775fab2ad1edad0ad31e0b80774180'
        ref: 'main'
        path: 'cidr-gist'
        fetch-depth: 0
        token: ${{ secrets.GIST_TOKEN }}
        github-server-url: 'https://gist.github.com'

    - name: Push to gist
      run: |
        cp -f cidrs/netflix-aws.txt cidr-gist/
        cp -f cidrs/netflix-aws-us-west-2.txt cidr-gist/
        cp -f cidrs/non-china-list.txt cidr-gist/non-china.txt
        cp -f cidrs/china-list.txt cidr-gist/china.txt
        cp -f cidrs/valve.txt cidr-gist/
        cp -f cidrs/zscaler.txt cidr-gist/
        cd cidr-gist

        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m 'Update CIDRs' || true
        ../.github/workflows/cidr-metadata.bash > README.md
        git add README.md
        git commit -m 'Update metadata' || true
        git push origin HEAD || true
