# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build isolated-vm

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-16.04, macos-latest]
        node-version: [10.x, 12.x, 14.x, 15.x]
        include:
          - os: ubuntu-16.04
            CC: gcc-5
            CXX: g++-5
    env:
      CC: ${{ matrix.CC }}
      CXX: ${{ matrix.CXX }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        cd release-isolated-vm
        export CC=${CC:-gcc}
        export CXX=${CXX:-g++}
        echo $CC $CXX
        type "$CC"
        type "$CXX"
        npm ci || npm install
